### ISSUE TITLE
nginx-1.9.[0-2]版本编译模块时不能通过

### ISSUE THREAD

**Issue by yinyalan** [xiaokai-wang/nginx-stream-upsync-module#1]
在使用nginx-1.9.[0-2]版本的源码上编译改模块的代码时报如下错误：
/nginx-stream-upsync-module/src/ngx_stream_upsync_module.c
./nginx-stream-upsync-module/src/ngx_stream_upsync_module.c: In function ‘ngx_stream_upsync_del_delay_delete’:
./nginx-stream-upsync-module/src/ngx_stream_upsync_module.c:2935: error: ‘ngx_stream_upstream_t’ has no member named ‘start_sec’
make[1]: *** [objs/addon/src/ngx_stream_upsync_module.o] Error 1
make[1]: Leaving directory `/data/apps/opt/nginx-1.9.2'
make: *** [build] Error 2

**Comment by xiaokai-wang** [comment]
这是一个问题，感谢反馈

另nginx-1.9.0 才引入stream 模块，还有很多不完善，以及后续的几个版本。

本模块基于nginx-1.9.10 开发，所以建议用此版本，或后续版本，感谢！

**Comment by g522342435** [comment]
动态修改后，配置文件是否跟着更新？ 如果配置文件不更新，reload以后就恢复了！

**Comment by xiaokai-wang** [comment]
请开辟一个新的issue.

会把所有的server down下来，reload 不会恢复！
