### ISSUE TITLE
不兼容 nginx  1.11

### ISSUE THREAD

**Issue by xianhuawei** [xiaokai-wang/nginx-stream-upsync-module#15]
编译报错

	/root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c
/root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c:304:5: error: initialization from incompatible pointer type [-Werror]
     ngx_stream_upsync_create_main_conf,         /* create main configuration */
     ^
/root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c:304:5: error: (near initialization for ‘ngx_stream_upsync_module_ctx.postconfiguration’) [-Werror]
/root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c:305:5: error: initialization from incompatible pointer type [-Werror]
     ngx_stream_upsync_init_main_conf,           /* init main configuration */
     ^
/root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c:305:5: error: (near initialization for ‘ngx_stream_upsync_module_ctx.create_main_conf’) [-Werror]
/root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c:307:5: error: initialization from incompatible pointer type [-Werror]
     ngx_stream_upsync_create_srv_conf,          /* create server configuration */
     ^
/root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c:307:5: error: (near initialization for ‘ngx_stream_upsync_module_ctx.init_main_conf’) [-Werror]
/root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c:309:1: error: missing initializer for field ‘merge_srv_conf’ of ‘ngx_stream_module_t’ [-Werror=missing-field-initializers]
 };
 ^
In file included from /root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c:8:0:
src/stream/ngx_stream.h:236:36: note: ‘merge_srv_conf’ declared here
     char                        *(*merge_srv_conf)(ngx_conf_t *cf, void *prev,
                                    ^
/root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c: In function ‘ngx_stream_upsync_show’:
/root/nginx-stream-upsync-module-master/src/ngx_stream_upsync_module.c:3704:9: error: implicit declaration of function ‘ngx_stream_close_connection’ [-Werror=implicit-function-declaration]
         ngx_stream_close_connection(s->connection);
         ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_stream_upsync_module.o] Error 1
make[1]: Leaving directory `/root/nginx-1.11.5'

**Comment by xiaokai-wang** [comment]
Thanks for your report.

nginx-1.11 stream 的数据结构做了变动，所以会出现报错.

已更新，请使用nginx-1.11+ 分支. 感谢！

**Comment by gfrankliu** [comment]
Can we use #if to wrap those changes and get rid of the branch?

#if nginx_version >= 1011000
