### ISSUE TITLE
consul 

### ISSUE THREAD

**Issue by trestea** [xiaokai-wang/nginx-stream-upsync-module#17]
请问 ：
upsync 172.17.0.2:8500/v1/kv/upstreams/test upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;  这个配置是在nginx配置文件里面写的 ，意思是从consul拉去配置 ，但是 consul里面的配置  用什么方法自动注册上去 供nginx-stream-upsync-module  自动拉去，你能不能把实践贴出来

**Comment by xiaokai-wang** [comment]
去consul 注册的话，需要自己去注册

参考：https://github.com/xiaokai-wang/nginx-stream-upsync-module#consul_interface
