### ISSUE TITLE
nginx-1.11+分支报以下错误，是什么原因呢

### ISSUE THREAD

**Issue by Corson011** [xiaokai-wang/nginx-stream-upsync-module#20]
nginx-stream-upsync-module-nginx-1.11/src/ngx_stream_upsync_module.c:3766: undefined reference to `ngx_stream_finalize_session'
collect2: error: ld returned 1 exit status

ngx_stream_finalize_session(s, NGX_OK);--报这个调用的问题，是我少了什么吗

**Comment by xiaokai-wang** [comment]
你的nginx 是什么版本？

**Comment by Corson011** [comment]
Nginx-1.11.2

**Comment by xiaokai-wang** [comment]
可以的话，麻烦试一下 nginx-1.11.3

**Comment by gfrankliu** [comment]
Please re-open and report back if you still have issues with newer nginx releases.
