### ISSUE TITLE
nginx-stream-upsycn-module 和 nginx-upsync-module 同时编译出错

### ISSUE THREAD

**Issue by JackyAn82** [xiaokai-wang/nginx-stream-upsync-module#24]
Hi,
我现在用的是nginx.1.13.1，不能同时编译提到的两个模块，也看到其他的人问过类似的问题。 我尝试去用https://github.com/CallMeFoxie/nginx-upsync/去加载两个模块，但是仍然报错
![image](https://user-images.githubusercontent.com/34223897/33534327-b6ba8e2a-d8e1-11e7-843b-6e1b9486b03e.png)
![image](https://user-images.githubusercontent.com/34223897/33534342-c4ef5e30-d8e1-11e7-9b52-107836d504b5.png)
请问，有没有更新的版本对于https://github.com/CallMeFoxie/nginx-upsync/，或者这个集成的模块最高支持的nginx版本是多少？ 
谢谢

**Comment by coagent** [comment]
我也遇到相同的问题，不能同时使用两个模块。

**Comment by xiaokai-wang** [comment]
please refer to https://github.com/xiaokai-wang/nginx-upsync

@coagent can you tell more detail?

**Comment by gfrankliu** [comment]
I just merged the fix in nginx-stream-upsync-module. Can you check out and try again?
