### ISSUE TITLE
nginx-1.12.2版本编译安装出现如下错误，求解

### ISSUE THREAD

**Issue by 527593036** [xiaokai-wang/nginx-stream-upsync-module#26]
版本： nginx-1.12.2

编译命令：./configure --prefix=/usr/local/nginx-1.12.2 --with-stream --add-module=../nginx-upsync && make -j4

出现如下错误：
../nginx-upsync/nginx-stream-upsync-module/src/ngx_stream_upsync_module.c: In function 'ngx_stream_upsync_replace_peers':
../nginx-upsync/nginx-stream-upsync-module/src/ngx_stream_upsync_module.c:1181:53: error: variable 'tmp_peer' set but not used [-Werror=unused-but-set-variable]
ngx_stream_upstream_rr_peer_t *peer = NULL, *tmp_peer;
^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_stream_upsync_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/usr/local/src/nginx/nginx-1.12.2'
make: *** [build] Error 2

**Comment by xiaokai-wang** [comment]
已修复，感谢反馈.
