### ISSUE TITLE
dump文件没有保存已存在的server

### ISSUE THREAD

**Issue by TwitchChen** [xiaokai-wang/nginx-stream-upsync-module#32]
请问为什么我upstream内容更新了，但是dump文件中还是第一次启动时候我写的内容，不应该是dump 新的upstream信息么？
>dump 文件内容
```
# cat dump_conf/servers_test.conf 
server 127.0.0.1:80 weight=1 fail_timeout=8 max_fails=3;
```

>upstream 信息
```
# curl 127.0.0.1:10000/upstream_show
Upstream name: test; Backend server count: 3
        server 127.0.0.1:9002 weight=1 max_fails=2 fail_timeout=10s;
        server 127.0.0.1:9001 weight=1 max_fails=2 fail_timeout=10s;
        server 127.0.0.1:9000 weight=1 max_fails=2 fail_timeout=10s;
```

> nginx conf文件

````
upstream test {
    upsync 127.0.0.1:8500/v1/kv/upstreams/test/ upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
    upsync_dump_path /opt/nginx/conf/db-site/dump_conf/servers_test.conf;
    
    include /opt/nginx/conf/db-site/dump_conf/servers_test.conf;
}

server {
    listen 10001;
    proxy_connect_timeout 3s;
    proxy_timeout 5s;
    proxy_pass test;
}
server {
    listen 10000;
    upstream_show;
}
````

**Comment by gfrankliu** [comment]
nginx user needs to have write permission to the directory "dump_conf"

**Comment by TwitchChen** [comment]
@gfrankliu thanks， i will have a try.
Well, i have  another question.
when i first start nginx, the nginx conf and dump file just like above.the consul have the kv(like above) already before nginx start. but the nginx upstream have nothing except the dump file server,why?
![image](https://user-images.githubusercontent.com/18111540/47332439-da9bd000-d6b1-11e8-9ddd-4940cf4cacc2.png)

**Comment by TwitchChen** [comment]
I have solved this problem. it's also caused by the nginx file permission .thanks
