### ISSUE TITLE
ngx_stream_upsync_del_peers 出现 coredump 

### ISSUE THREAD

**Issue by fishgege** [xiaokai-wang/nginx-stream-upsync-module#41]
ngx_stream_upsync_del_peers 中   tmp_del_peer->next = NULL;
这一行会引发coredump， tmp_del_peer 在没有匹配到的时候是个空值

**Comment by xiaokai-wang** [comment]
这是必现的吗？你能试着修复一下吗？感谢

**Comment by fishgege** [comment]
可以的， 无匹配项场景下必现

**Comment by fishgege** [comment]
fix
