### ISSUE TITLE
Stream

### ISSUE THREAD

**Issue by daxiong380380** [xiaokai-wang/nginx-stream-upsync-module#8]
xiaokai哥你好
我在stream-lua-nginx-module板块提了一个问题，你让我尝试使用nginx-stream-upsync-module来解决，我发现这个模块貌似不能满足我的要求，我现在的困惑是：我能否通过解析TCP流来确定我要转发的路由，因为我看到openresty转发http数据是可以的。
由于我是刚刚入门openresty，一些相关的知识不是很熟，所以麻烦xiaokai哥帮忙解答一下

**Comment by xiaokai-wang** [comment]
http 可以，但是tcp 流现在貌似还做不到，这个module 不能满足你的需求，抱歉！

**Comment by daxiong380380** [comment]
噢  stream模块是不是处在开发阶段啊，后面是不是也会做成类似http那样

**Comment by xiaokai-wang** [comment]
本模块基本开发已经结束，以后可能需要添加一些feature；

stream_lua 据我所知还在完善阶段，至于会不会像http 模块那样，这个很难说；

**Comment by daxiong380380** [comment]
xiaokai哥 有没有其他的办法能解决我的问题

**Comment by daxiong380380** [comment]
set ,access_by_lua_block这些directive为什么没有在stream模块实现呢

**Comment by xiaokai-wang** [comment]
正在进行时吧

**Comment by daxiong380380** [comment]
@xiaokai-wang 意思是这个已经在开发吗，能不能帮忙确认一下，进展如何了。
假设这几个directive实现了，那我理解是不是我的难题可以解决了。
非常感谢xiaokai哥

**Comment by xiaokai-wang** [comment]
抱歉，这个你还是去咨询章哥吧，lua系列的作者
