### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by zhangkaitao** [xiaokai-wang/nginx-stream-upsync-module#9]
nginx version: nginx/1.10.1
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
configure arguments: --prefix=/usr/servers/nginx --with-stream --add-module=../openresty-1.9.7.4/nginx-stream-upsync-module-1.0.0/

    upstream mysql_backend {
        least_conn;
        server 127.0.0.1:1111;
        upsync 127.0.0.1:8500/v1/kv/upstreams/mysql_backend upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /usr/servers/nginx/conf/mysql_backend.conf;
        upsync_lb least_conn;
    }

当配置了upsync_lb least_conn时 worker进程会一直exit。
2016/10/09 22:54:44 [alert] 67211#0: worker process 67245 exited on signal 11 (core dumped)
2016/10/09 22:54:44 [alert] 67211#0: worker process 67247 exited on signal 11 (core dumped)
2016/10/09 22:54:44 [alert] 67211#0: worker process 67249 exited on signal 11 (core dumped)
2016/10/09 22:54:44 [alert] 67211#0: worker process 67251 exited on signal 11 (core dumped)
2016/10/09 22:54:45 [alert] 67211#0: worker process 67253 exited on signal 11 (core dumped)

**Comment by zhangkaitao** [comment]
另外当reload时，work一直不退出。
root@ubuntu:/usr/servers/nginx# ps -aux | grep nginx
root      73820  0.0  0.1  35756  1232 ?        Ss   22:58   0:00 nginx: master process ./sbin/nginx
nobody    75264  0.0  0.5  40336  5728 ?        S    23:00   0:00 nginx: worker process is shutting down
nobody    75293  0.0  0.5  36128  5732 ?        S    23:01   0:00 nginx: worker process

**Comment by xiaokai-wang** [comment]
抱歉 least_conn 数据结构应该是从nginx-1.9.0 开始就改变了，一直没有更新，周末进行更新；

work 进程需要多久才能退出呢？上次做了一个改进，应该可以尽快退出吧？

**Comment by zhangkaitao** [comment]
我测试时，至少5分钟没有退出，没有连接的情况下reload的。

2016-10-10 23:37 GMT+08:00 xiaokai <notifications@github.com>:

**Comment by xiaokai-wang** [comment]
hi @zhangkaitao ,

我试了nginx-1.9.10 和 nginx-1.10.1 在mac os 10.11.5，reload 时，旧的work 进程都可以即时退出（在无流量的情况下）；在centos 2.6.32 上尝试了nginx-1.10.1 也是可以即时退出的；麻烦再尝试一下

这个延迟退出之前是存在的，但是改进后，就不存在了

谢！

**Comment by zhangkaitao** [comment]
没问题了。
